### ISSUE TITLE
Docs wasn’t build successfull.

### ISSUE THREAD

**Issue by tuna2134** [atroche/rust-headless-chrome#355]

**Comment by Billy-Sheppard** [comment]
Error: `Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }`

Cause (guess): Writing to the filesystem in the build.rs.

I'll look into this, thanks for the bug report.

**Comment by Billy-Sheppard** [comment]
Ok looks like this was fixed in [auto_generate_cdp](https://github.com/mdrokz/auto_generate_cdp) `v0.4.0`

I'll bump the cargo version, it should also fix this: https://github.com/atroche/rust-headless-chrome/issues/353

**Comment by Billy-Sheppard** [comment]
The most recent build now receives this error:

```rust
thread 'main' panicked at incorrect file name: 
    Transport(
        Transport { 
            kind: Dns,
            message: Some("resolve dns name 'raw.githubusercontent.com:443'"),
            url: Some(Url { scheme: "https",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: Some(Domain("raw.githubusercontent.com")),
            port: None,
            path: "/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json",
            query: None,
            fragment: None }),
            source: Some(
                Custom { 
                    kind: Uncategorized,
                    error: "failed to lookup address information: Temporary failure in name resolution" 
                }
            ) 
        }
    )
, /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/auto_generate_cdp-0.4.0/src/compile.rs:1268:10
```

The thing bugging out seems to be this:
```rust
    let url = format!(
        "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/{}/json/{}",
        commit, file_name
    );

    let json = ureq::get(&url)
        .call()
        .expect("incorrect file name")
        .into_string()
        .unwrap();
```
However both:
- https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json and,
- https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/browser_protocol.json

seem to work as links.

I'm unsure about how to fix this one.

**Comment by mdrokz** [comment]
> The most recent build now receives this error:
> 
> ```rust
> thread 'main' panicked at incorrect file name: 
>     Transport(
>         Transport { 
>             kind: Dns,
>             message: Some("resolve dns name 'raw.githubusercontent.com:443'"),
>             url: Some(Url { scheme: "https",
>             cannot_be_a_base: false,
>             username: "",
>             password: None,
>             host: Some(Domain("raw.githubusercontent.com")),
>             port: None,
>             path: "/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json",
>             query: None,
>             fragment: None }),
>             source: Some(
>                 Custom { 
>                     kind: Uncategorized,
>                     error: "failed to lookup address information: Temporary failure in name resolution" 
>                 }
>             ) 
>         }
>     )
> , /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/auto_generate_cdp-0.4.0/src/compile.rs:1268:10
> ```
> 
> The thing bugging out seems to be this:
> 
> ```rust
>     let url = format!(
>         "https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/{}/json/{}",
>         commit, file_name
>     );
> 
>     let json = ureq::get(&url)
>         .call()
>         .expect("incorrect file name")
>         .into_string()
>         .unwrap();
> ```
> 
> However both:
> 
> * https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json and,
> * https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/browser_protocol.json
> 
> seem to work as links.
> 
> I'm unsure about how to fix this one.

let me take a look as soon as i get more time

**Comment by Billy-Sheppard** [comment]
I think [auto_generate_cdp](https://github.com/mdrokz/auto_generate_cdp) needs to have a version bump to 0.4.1 for this to propagate through, docs are still failing because it's pulling the 0.4.0 version from crates.io rather than the updated github release.

**Comment by mdrokz** [comment]
> I think [auto_generate_cdp](https://github.com/mdrokz/auto_generate_cdp) needs to have a version bump to 0.4.1 for this to propagate through, docs are still failing because it's pulling the 0.4.0 version from crates.io rather than the updated github release.

Yes i was planning to do that and i didn't expect this issue to get closed automatically, I mentioned it in the PR for auto_generate_cdp

**Comment by mdrokz** [comment]
> I think [auto_generate_cdp](https://github.com/mdrokz/auto_generate_cdp) needs to have a version bump to 0.4.1 for this to propagate through, docs are still failing because it's pulling the 0.4.0 version from crates.io rather than the updated github release.

@Billy-Sheppard i pushed a new version of auto_generate_cdp, Can you use that in headless chrome and publish a new version ?

**Comment by Billy-Sheppard** [comment]
@mdrokz - I've had a go this morning to try and get this working but it still seems its not set up right - the if statement works fine, but perhaps I don't have the .json file in the correct location/name?

**Comment by mdrokz** [comment]
> @mdrokz - I've had a go this morning to try and get this working but it still seems its not set up right - the if statement works fine, but perhaps I don't have the .json file in the correct location/name?

Are you building locally ? if so this variable should be set `CARGO_MANIFEST_DIR`

**Comment by Billy-Sheppard** [comment]
The docs build is still failing https://docs.rs/crate/headless_chrome/1.0.4/builds/737673

**Comment by Billy-Sheppard** [comment]
This is now fixed.
